<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Persona', 'doctrine');

/**
 * BasePersona
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dni
 * @property string $first_name
 * @property string $last_name
 * @property string $email_address
 * @property integer $telefono
 * @property string $direccion
 * @property integer $genero
 * 
 * @method integer getDni()           Returns the current record's "dni" value
 * @method string  getFirstName()     Returns the current record's "first_name" value
 * @method string  getLastName()      Returns the current record's "last_name" value
 * @method string  getEmailAddress()  Returns the current record's "email_address" value
 * @method integer getTelefono()      Returns the current record's "telefono" value
 * @method string  getDireccion()     Returns the current record's "direccion" value
 * @method integer getGenero()        Returns the current record's "genero" value
 * @method Persona setDni()           Sets the current record's "dni" value
 * @method Persona setFirstName()     Sets the current record's "first_name" value
 * @method Persona setLastName()      Sets the current record's "last_name" value
 * @method Persona setEmailAddress()  Sets the current record's "email_address" value
 * @method Persona setTelefono()      Sets the current record's "telefono" value
 * @method Persona setDireccion()     Sets the current record's "direccion" value
 * @method Persona setGenero()        Sets the current record's "genero" value
 * 
 * @package    tweetme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersona extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('persona');
        $this->hasColumn('dni', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             'length' => 10,
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('telefono', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('direccion', 'string', 35, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 35,
             ));
        $this->hasColumn('genero', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}