<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/01/23 17:08:27
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
);
