<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/01/23 17:19:01
sfConfig::add(array(
  'mod_sfguardforgotpassword_enabled' => true,
  'mod_sfguardforgotpassword_view_class' => 'sfPHP',
));
