<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/01/23 17:08:27
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
);
