<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/01/16 18:34:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tweetme',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
